//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPlaceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string itemid { get; set; }
        public string catid { get; set; }
        public string subid { get; set; }
        public string addedby { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
